[2024-08-03T08:40:18.745+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-03T08:40:18.755+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather-app.transform_weather_data scheduled__2024-08-02T00:00:00+00:00 [queued]>
[2024-08-03T08:40:18.761+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather-app.transform_weather_data scheduled__2024-08-02T00:00:00+00:00 [queued]>
[2024-08-03T08:40:18.761+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 3
[2024-08-03T08:40:18.778+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_weather_data> on 2024-08-02 00:00:00+00:00
[2024-08-03T08:40:18.784+0000] {standard_task_runner.py:64} INFO - Started process 2485 to run task
[2024-08-03T08:40:18.788+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather-app', 'transform_weather_data', 'scheduled__2024-08-02T00:00:00+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/weather_dags.py', '--cfg-path', '/tmp/tmpgm9jvncs']
[2024-08-03T08:40:18.788+0000] {standard_task_runner.py:91} INFO - Job 62: Subtask transform_weather_data
[2024-08-03T08:40:18.827+0000] {task_command.py:426} INFO - Running <TaskInstance: weather-app.transform_weather_data scheduled__2024-08-02T00:00:00+00:00 [running]> on host ip-172-31-15-224.ap-southeast-2.compute.internal
[2024-08-03T08:40:18.887+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather-app' AIRFLOW_CTX_TASK_ID='transform_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-02T00:00:00+00:00'
[2024-08-03T08:40:18.888+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-03T08:40:19.270+0000] {credentials.py:550} INFO - Found credentials from IAM Role: ec2-s3
[2024-08-03T08:40:19.473+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-08-03T08:40:19.474+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-03T08:40:19.479+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather-app, task_id=transform_weather_data, run_id=scheduled__2024-08-02T00:00:00+00:00, execution_date=20240802T000000, start_date=20240803T084018, end_date=20240803T084019
[2024-08-03T08:40:19.521+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-03T08:40:19.533+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-03T08:40:19.534+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
