[2024-08-03T08:39:40.755+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-03T08:39:40.765+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather-app.transform_weather_data manual__2024-08-03T08:34:27.514176+00:00 [queued]>
[2024-08-03T08:39:40.771+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather-app.transform_weather_data manual__2024-08-03T08:34:27.514176+00:00 [queued]>
[2024-08-03T08:39:40.771+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 3
[2024-08-03T08:39:40.787+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_weather_data> on 2024-08-03 08:34:27.514176+00:00
[2024-08-03T08:39:40.793+0000] {standard_task_runner.py:64} INFO - Started process 2440 to run task
[2024-08-03T08:39:40.796+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather-app', 'transform_weather_data', 'manual__2024-08-03T08:34:27.514176+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/weather_dags.py', '--cfg-path', '/tmp/tmp74dxcche']
[2024-08-03T08:39:40.797+0000] {standard_task_runner.py:91} INFO - Job 61: Subtask transform_weather_data
[2024-08-03T08:39:40.833+0000] {task_command.py:426} INFO - Running <TaskInstance: weather-app.transform_weather_data manual__2024-08-03T08:34:27.514176+00:00 [running]> on host ip-172-31-15-224.ap-southeast-2.compute.internal
[2024-08-03T08:39:40.895+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather-app' AIRFLOW_CTX_TASK_ID='transform_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-03T08:34:27.514176+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-03T08:34:27.514176+00:00'
[2024-08-03T08:39:40.896+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-03T08:39:41.288+0000] {credentials.py:550} INFO - Found credentials from IAM Role: ec2-s3
[2024-08-03T08:39:41.491+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-08-03T08:39:41.491+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-03T08:39:41.496+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather-app, task_id=transform_weather_data, run_id=manual__2024-08-03T08:34:27.514176+00:00, execution_date=20240803T083427, start_date=20240803T083940, end_date=20240803T083941
[2024-08-03T08:39:41.530+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-03T08:39:41.542+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-03T08:39:41.542+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
