[2024-07-31T19:18:11.326+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-31T19:18:11.332+0000] {taskinstance.py:2066} INFO - Dependencies not met for <TaskInstance: weather-app.is_weather_api_ready scheduled__2024-07-30T00:00:00+00:00 [up_for_retry]>, dependency 'Not In Retry Period' FAILED: Task is not ready for retry yet but will be retried automatically. Current date is 2024-07-31T19:18:11.332405+00:00 and task will be retried at 2024-07-31T19:23:07.568379+00:00.
[2024-07-31T19:18:11.337+0000] {local_task_job_runner.py:163} INFO - Task is not able to be run
[2024-07-31T19:23:39.712+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-31T19:23:39.725+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather-app.is_weather_api_ready scheduled__2024-07-30T00:00:00+00:00 [queued]>
[2024-07-31T19:23:39.731+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather-app.is_weather_api_ready scheduled__2024-07-30T00:00:00+00:00 [queued]>
[2024-07-31T19:23:39.731+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 3
[2024-07-31T19:23:39.747+0000] {taskinstance.py:2330} INFO - Executing <Task(HttpSensor): is_weather_api_ready> on 2024-07-30 00:00:00+00:00
[2024-07-31T19:23:39.752+0000] {standard_task_runner.py:64} INFO - Started process 5903 to run task
[2024-07-31T19:23:39.754+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather-app', 'is_weather_api_ready', 'scheduled__2024-07-30T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/weather_dags.py', '--cfg-path', '/tmp/tmpn1bfoeb4']
[2024-07-31T19:23:39.755+0000] {standard_task_runner.py:91} INFO - Job 11: Subtask is_weather_api_ready
[2024-07-31T19:23:39.792+0000] {task_command.py:426} INFO - Running <TaskInstance: weather-app.is_weather_api_ready scheduled__2024-07-30T00:00:00+00:00 [running]> on host ip-172-31-15-224.ap-southeast-2.compute.internal
[2024-07-31T19:23:39.856+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather-app' AIRFLOW_CTX_TASK_ID='is_weather_api_ready' AIRFLOW_CTX_EXECUTION_DATE='2024-07-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-30T00:00:00+00:00'
[2024-07-31T19:23:39.857+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-31T19:23:39.858+0000] {baseoperator.py:400} WARNING - HttpSensor.execute cannot be called outside TaskInstance!
[2024-07-31T19:23:39.858+0000] {http.py:137} INFO - Poking: /data/2.5/weather?q=Portland&appid=e1c2b88664f3211ebc372dda792b7c58
[2024-07-31T19:23:39.863+0000] {base.py:84} INFO - Using connection ID 'weatherapp_api' for task execution.
[2024-07-31T19:23:40.169+0000] {base.py:294} INFO - Success criteria met. Exiting.
[2024-07-31T19:23:40.169+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-31T19:23:40.174+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather-app, task_id=is_weather_api_ready, run_id=scheduled__2024-07-30T00:00:00+00:00, execution_date=20240730T000000, start_date=20240731T192339, end_date=20240731T192340
[2024-07-31T19:23:40.207+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-31T19:23:40.218+0000] {logging_mixin.py:188} WARNING - /home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/models/baseoperator.py:1297 AirflowProviderDeprecationWarning: Call to deprecated class SimpleHttpOperator. (Class `SimpleHttpOperator` is deprecated and will be removed in a future release. Please use `HttpOperator` instead.)
[2024-07-31T19:23:40.234+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-31T19:23:40.241+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
